name: CD

on:
  release:
    types: [ created ]

defaults:
  run:
    shell: bash

# required for upload
permissions:
  contents: write

jobs:

  Linux:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ ubuntu-24.04, ubuntu-24.04-arm ]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update -y && sudo apt install -y build-essential cmake python3 zip

      - name: Build
        run: ./build_gdlibretro.sh

      - name: Compress
        run: zip -r -9 "gdlibretro-${{ runner.os }}-${{ runner.arch }}.zip" addons/LibRetroHost.gdextension addons/*.so
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            *.zip

  MacOS:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ macos-latest, macos-13 ]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: brew update && brew install cmake python zip

      - name: Build
        run: ./build_gdlibretro.sh

      - name: Compress
        run: zip -r -9 "gdlibretro-${{ runner.os }}-${{ runner.arch }}.zip" addons/LibRetroHost.gdextension addons/*.dylib

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            *.zip            

  Windows:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ windows-latest ]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: choco install zip

      - name: Set up Visual Studio (MSVC)
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 'latest'
        
      - name: Build
        run: |
            cd gdlibretro
            cmake -DNO_GIT_REVISION=ON -DCMAKE_BUILD_TYPE=Debug -B build
            cmake --build build
            dir build

      - name: Compress
        run: zip -r -9 "gdlibretro-${{ runner.os }}-${{ runner.arch }}.zip" addons/LibRetroHost.gdextension gdlibretro/build/LibRetroHost/lib/Windows-AMD64/Debug/LibRetroHost-d.dll

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            *.zip            
